### PR TITLE
Allow for optional `alg` in JWK

### PR DESCRIPTION
**Pull request by ccakes**
ref #127 

Only validate token `alg` against JWK in `Compact::decode_with_jwks` if
the JWK has a value

### CODE REVIEW

**Comment by lawliet89** [comment]
I'll look into this once I solve some build and test issues. Sorry for the delay.

**Comment by lawliet89** [comment]
I will be including your commit as part of #130 

I have modified your PR to require an expected algorithm in the absence of one from the JWK.

This is to deal with this issue: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by lawliet89** [comment]
Closing this PR because your commit has been squashed and merged as part of https://github.com/lawliet89/biscuit/commit/f62cd39bbe35268c9a2286290af90f5cd811c01a

**Comment by psoots** [comment]
If the `alg` is not specified by the key in JWKS, why not use the `alg` from the JWT header?

**Pull request closed without merging**
