### PR TITLE
Remove dependency on time 0.1

### PR DESCRIPTION
**Pull request by g2p**
Disabling chrono default features allows removing an unnecessary dependency.

### CODE REVIEW

**Review by lawliet89 — APPROVED** [review]

**Comment by lawliet89** [comment]
Thanks.

**Comment by complexspaces** [comment]
Hi there,

Would you be willing to make a crates.io release that includes these changes if time permits?

**Comment by lawliet89** [comment]
@complexspaces I've published 0.6.0. Sorry for the wait.

**Comment by complexspaces** [comment]
Thanks a bunch for doing that, its appreciated.

**Pull request merged**
